### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1309]
Our CI build for Android failed: https://github.com/get10101/10101/actions/runs/6220173722/job/16879658066

```
 │ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Users/runner/work/10101/10101/mobile/android/build.gradle:                         │
│ ext.kotlin_version = '<latest-version>'              
```

Looks like we downgraded/upgraded a version.

**Comment by holzeis** [comment]
Should be fixed with https://github.com/get10101/10101/pull/1310/commits/ee22c0de2022104fd878c7e4f058cb4bc76d4574

**Comment by bonomat** [comment]
Was not fixed unfortunately. 

This ticket is related: https://github.com/fastlane/fastlane/issues/21091

**Comment by bonomat** [comment]
https://github.com/get10101/10101/pull/1311 did not fix it neither, trying the second recommendation from https://github.com/fastlane/fastlane/issues/21091 and bump fastlane

**Comment by bonomat** [comment]
With the latest fix it seems to be mitigated by simply retrying up to 5 times.
